package mod.fossilsarch2.world;

import mod.fossilsarch2.FossilsArch2Mod;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.neoforged.neoforge.common.world.BiomeModifier;

/**
 * Holds the keys for this mod's worldgen. Actual placement now lives in datapack
 * JSON under {@code data/fossilsarch2/neoforge/biome_modifier/}, generated by the
 * datagen pipeline. Runtime registration of features is no longer needed under
 * NeoForge — biome modifiers are loaded from the registry.
 */
public final class ModWorldGeneration {

	public static final ResourceKey<PlacedFeature> FOSSIL_ORE_PLACED = ResourceKey.create(
			Registries.PLACED_FEATURE, Identifier.fromNamespaceAndPath(FossilsArch2Mod.MOD_ID, "fossil_ore"));

	public static final ResourceKey<BiomeModifier> ADD_FOSSIL_ORE = ResourceKey.create(
			net.neoforged.neoforge.registries.NeoForgeRegistries.Keys.BIOME_MODIFIERS,
			Identifier.fromNamespaceAndPath(FossilsArch2Mod.MOD_ID, "add_fossil_ore"));

	private ModWorldGeneration() {}
}
